### ISSUE TITLE
Analysis of additional components to be made configurable

### ISSUE THREAD

**Issue by senfmal** [senfmal/confluence_monitor#14]
Potentially almost everything useful is already made configuable. However, a thorough anaylsis needs to be done.

**Comment by senfmal** [comment]
- [ ] main.py --> CLI command needs to be re-worked as this is still referencing to command line configuration. This configuration is hard-coded and is basing on original assumptions of the underlying context
- [ ] main.py --> if no config.json is available, monitor needs to open without a configuration, allowing the user to load one or to create one via GUI
- [ ] Confluence_Monitor.bat --> installer and loader is out-dated, at the moment it's of no use. Also, at the moment, there is only a Windows based batch script
- [ ] confluence\ConfLastUpdated.py --> within acquire_conf_connection()-method, the api_root attribute is hard coded as "wiki/rest/api", which should be be part of the configuration schema
- [ ] gui\LoginFrame.py --> nothing to do here
- [ ] gui\MainWindow.py --> untagged type is completely hard-coded. However, to some extend, this needs to be hard-wired, but sorting etc. my be part of the configuration schema (with a default config if missing)
- [ ] gui\MainWindow.py --> config_environ()-method, the filter variables are all set to 1 (i.e. filter should include category). This needs to be part of the configuration schema (with a default 0 if not config'ed in the schema)

**Comment by senfmal** [comment]
- [x] main.py --> CLI command needs to be re-worked as this is still referencing to command line configuration. This configuration is hard-coded and is basing on original assumptions of the underlying context --> issue #16 
- [x] main.py --> if no config.json is available, monitor needs to open without a configuration, allowing the user to load one or to create one via GUI --> issue #17
- [x] Confluence_Monitor.bat --> installer and loader is out-dated, at the moment it's of no use. Also, at the moment, there is only a Windows based batch script --> issue #18 
- [x] confluence\ConfLastUpdated.py --> within acquire_conf_connection()-method, the api_root attribute is hard coded as "wiki/rest/api", which should be be part of the configuration schema --> issue #19 
- [x] gui\LoginFrame.py --> nothing to do here
- [x] gui\MainWindow.py --> untagged type is completely hard-coded. However, to some extend, this needs to be hard-wired, but sorting etc. my be part of the configuration schema (with a default config if missing) --> issue #20 
- [x] gui\MainWindow.py --> config_environ()-method, the filter variables are all set to 1 (i.e. filter should include category). This needs to be part of the configuration schema (with a default 0 if not config'ed in the schema) --> issue #21 

ANALYSIS DONE to this extend. All identified enhancements documented in referred issues!
